// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXTGvrihLgV0GGOYJ75T_dJ7eO3EzxRbI',
    appId: '1:228448977128:web:c393ca63c19434da19095d',
    messagingSenderId: '228448977128',
    projectId: 'chat-09062003',
    authDomain: 'chat-09062003.firebaseapp.com',
    storageBucket: 'chat-09062003.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC7zyQPsa9ZhdUtI5d7o5rY8egQPLoMe4',
    appId: '1:228448977128:android:2d0237a72f74017819095d',
    messagingSenderId: '228448977128',
    projectId: 'chat-09062003',
    storageBucket: 'chat-09062003.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAulR7YF1YEMnFDK5IIR1TBri1elXSKCkc',
    appId: '1:228448977128:ios:28db3141ed3129c019095d',
    messagingSenderId: '228448977128',
    projectId: 'chat-09062003',
    storageBucket: 'chat-09062003.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAulR7YF1YEMnFDK5IIR1TBri1elXSKCkc',
    appId: '1:228448977128:ios:28db3141ed3129c019095d',
    messagingSenderId: '228448977128',
    projectId: 'chat-09062003',
    storageBucket: 'chat-09062003.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXTGvrihLgV0GGOYJ75T_dJ7eO3EzxRbI',
    appId: '1:228448977128:web:143e887b125cb8be19095d',
    messagingSenderId: '228448977128',
    projectId: 'chat-09062003',
    authDomain: 'chat-09062003.firebaseapp.com',
    storageBucket: 'chat-09062003.appspot.com',
  );
}
